version: "3"

services:
  master:
    image: redis:alpine
    container_name: redis-master
    command: redis-server --requirepass 123456 --masterauth 123456
    ports:
      - "6379:6379"
    networks:
      redis-ha:
        ipv4_address: 172.23.0.3
        aliases: 
          - redis-master
    healthcheck:
      test: ["CMD", "redis-cli", "info"]
  slave1:
    image: redis:alpine
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379 --requirepass 123456 --masterauth 123456
    depends_on:
      - master
    networks:
      redis-ha:
        ipv4_address: 172.23.0.4
        aliases: 
          - redis-slave-1
    healthcheck:
      test: ["CMD", "redis-cli", "info"]
  slave2:
    image: redis:alpine
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-master 6379 --requirepass 123456 --masterauth 123456
    depends_on:
      - master
    networks:
      redis-ha:
        ipv4_address: 172.23.0.5
        aliases: 
          - redis-slave-2
    healthcheck:
      test: ["CMD", "redis-cli", "info"]
  sentinel1:
    image: redis:alpine
    container_name: redis-sentinel-1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "./sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel.conf"
    networks:
      redis-ha:
        ipv4_address: 172.23.0.6
        aliases: 
          - redis-sentinel-1
    depends_on: 
      - master
      - slave1
      - slave2
  sentinel2:
    image: redis:alpine
    container_name: redis-sentinel-2
    # ports:
    # - "26380:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "./sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel.conf"
    networks:
      redis-ha:
        ipv4_address: 172.23.0.7
        aliases: 
          - redis-sentinel-2
    depends_on: 
      - sentinel1
  sentinel3:
    image: redis:alpine
    container_name: redis-sentinel-3
    # ports:
    # - "26381:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "./sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel.conf"
    networks:
      redis-ha:
        ipv4_address: 172.23.0.8
        aliases: 
          - redis-sentinel-3
    depends_on: 
      - sentinel2
  monitor:
    image: transcranial/redmon:latest
    container_name: redmon
    ports:
    - "4567:4567"
    command: redmon -r redis://:123456@redis-master:6379
    networks:
      redis-ha:
        ipv4_address: 172.23.0.9
        aliases: 
          - redmon
  # redislive:
    # image: snakeliwei/redislive:latest
    # container_name: redislive
    # ports:
    # - "8888:8888"
    # command: ./redis-monitor.py --duration=3600 --quite
    # volumes: 
    #   - "./redislive/redis-live.conf:/redislive/src/redis-live.conf"
    # networks:
    #   redis-ha:
    #     aliases: 
    #       - redislive
  app:
    image: redisha/demoapp:0.1
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: demoapp
    networks:
      redis-ha:
        aliases: 
          - demoapp
    depends_on: 
      - master
      - slave1
      - slave2
      - sentinel1
      - sentinel2
      - sentinel3
  # benchmark:
  #   image: redislabs/memtier_benchmark:1.2.17
  #   container_name: benchmark
  #   command: memtier_benchmark -s redis-master -a 123456 --test-time 3600
  #   networks:
  #     - redis-ha

networks:
  redis-ha:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/24"
